feat(commitlint): add husky commit-msg with commitlint configuration
hwgilbert16/scholarsome pull request #119
Opened 2024-03-08 14:57 UTC by Jayanth-Parthsarathy

# Title
Fixes #118 .
Added `commitlint` and `husky` for linting commit messages using the semantics:

`<type>(<scope>): <subject>`

## Screenshots

![image](https://github.com/hwgilbert16/scholarsome/assets/86654557/69f277b8-b200-4ce5-b63b-703a121a42b5)

2024-03-08 21:26 UTC, hwgilbert16 requested changes
Looks good, but just move the new dependencies you added to devDependencies

2024-03-08 21:26 UTC, hwgilbert16 commented on package.json
Move the new commit linting dependencies to devDependencies

2024-03-09 03:43 UTC, Jayanth-Parthsarathy commented on package.json
> Move the new commit linting dependencies to devDependencies

Hey @hwgilbert16. I think the dependencies are already under `devDependencies`. Please feel free to correct me if I am wrong.

2024-03-09 05:42 UTC, hwgilbert16 commented on package.json
Ah, apologies. The web diff viewer made it seem as though the new dependencies were not under the correct category.

2024-03-09 05:42 UTC, hwgilbert16 approved these changes

2024-03-09 05:42 UTC, merged